### ISSUE TITLE
Image interest

### ISSUE THREAD

**Issue by kopax** [osixia/docker-openldap-backup#1]
What's the point of this image and all these executed scripts?
Is it not as simple to just tar the mounted volumes and move the backup from an host to another?

**Comment by osixia** [comment]
This image perform periodic hot backup. With some limitations : 
http://www.openldap.org/doc/admin24/maintenance.html
There is also some tools to restore a previous backup.

Indeed stopping the ldap server, backup the data volumes, restart the ldap is an other solution.
