### ISSUE TITLE
Can't make backup work

### ISSUE THREAD

**Issue by yarmenti** [osixia/docker-openldap-backup#3]
Hi,

Thanks a lot for all the Dockerfiles you provided. I've got some troubles using this image. I tried the following launch:
`docker run --name ldap-service --hostname ldap-service --env LDAP_BACKUP_DATA_CRON_EXP=“* * * * * *” --env LDAP_BACKUP_CONFIG_CRON_EXP=“* * * * * *” osixia/openldap-backup`
in order to make the backup every minute.

When entering into it; (`docker exec -it ldap-service /bin/bash`), I'm waiting for the backup to appear in `/data/backup`, but nothing happens. Could you help me? Maybe I'm wrong somewhere.

Thanks;

**Comment by osixia** [comment]
hello,
removing one * should do the trick :)

`docker run --name ldap-service --hostname ldap-service --env LDAP_BACKUP_DATA_CRON_EXP="* * * * *" --env LDAP_BACKUP_CONFIG_CRON_EXP="* * * * *" osixia/openldap-backup`

**Comment by yarmenti** [comment]
You're the best :)
Thanks,
