### ISSUE TITLE
outdated documentation?

### ISSUE THREAD

**Issue by gizero** [osixia/docker-openldap-backup#6]
Looks like the README is not pointing to the latest available tag (1.1.9 instead of 1.1.10). Is there a reason for that?

**Comment by osixia** [comment]
Hello,
version 1.1.10 is not released yet, but is available on docker hub to test.

v1.1.9 is the last release for now, docker hub latest tag point to this version.
v1.1.10 is available on docker hub to test but not officially released yet (see branch release-1.1.10 to see code)

The README on stable branch correspond to the last release version so 1.1.9 for now.

**Comment by BertrandGouny** [comment]
v1.1.10 is now released closing this :)
